In [1]:
## imports
import pandas as pd
import numpy as np
import re
import requests
import yaml


## repeated printouts
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# 1. Example 1: no credentials; no wrapper

Site: National Assessment of Education Progress (NAEP)

Documentation: https://www.nationsreportcard.gov/api_documentation.aspx

Base link: https://www.nationsreportcard.gov/DataService/GetAdhocData.aspx

## 1.1 Query to pull some data

In [2]:
## using their example query of 2011 writing scores separated by gender
## based on here - https://stackoverflow.com/questions/40836749/pythonic-way-of-writing-a-single-line-long-string
## using the ( ) syntax to formulate a long
## string without linebreaks added
example_naep_query = (
'https://www.nationsreportcard.gov/'
'Dataservice/GetAdhocData.aspx?'
'type=data&subject=writing&grade=8&'
'subscale=WRIRP&variable=GENDER&jurisdiction=NP&stattype=MN:MN&Year=2011')


example_naep_query

'https://www.nationsreportcard.gov/Dataservice/GetAdhocData.aspx?type=data&subject=writing&grade=8&subscale=WRIRP&variable=GENDER&jurisdiction=NP&stattype=MN:MN&Year=2011'

In [3]:
## use requests to call the api
naep_resp = requests.get(example_naep_query)
naep_resp
print(type(naep_resp))

## get the json contents of the response 
## here, we're assuming valid response
naep_resp_j = naep_resp.json()
naep_resp_j

## with result, turn it into a dataframe
naep_resp_d = pd.DataFrame(naep_resp_j['result'])
naep_resp_d

<class 'requests.models.Response'>

{'status': 200,
 'serviceVersion': '6.4.2026.1',
 'dwellTimeMS': '15.6285',
 'avgWebHostCPUTotalLoad': 'N/A',
 'dataHitType': 'FROM_MEMORY',
 'Source': 'B11A',
 'result': [{'year': 2011,
   'sample': 'R3',
   'yearSampleLabel': '2011',
   'Cohort': 2,
   'CohortLabel': 'Grade 8',
   'stattype': 'MN:MN',
   'subject': 'WRI',
   'grade': 8,
   'scale': 'WRIRP',
   'jurisdiction': 'NP',
   'jurisLabel': 'National public',
   'variable': 'GENDER',
   'variableLabel': 'Sex',
   'varValue': '1',
   'varValueLabel': 'Male',
   'value': 139.099504632971,
   'isStatDisplayable': 1,
   'errorFlag': 0},
  {'year': 2011,
   'sample': 'R3',
   'yearSampleLabel': '2011',
   'Cohort': 2,
   'CohortLabel': 'Grade 8',
   'stattype': 'MN:MN',
   'subject': 'WRI',
   'grade': 8,
   'scale': 'WRIRP',
   'jurisdiction': 'NP',
   'jurisLabel': 'National public',
   'variable': 'GENDER',
   'variableLabel': 'Sex',
   'varValue': '2',
   'varValueLabel': 'Female',
   'value': 158.567104984955,
   'isStatDisplayable': 1,
   'errorFlag': 0}]}

,year,sample,yearSampleLabel,Cohort,CohortLabel,stattype,subject,grade,scale,jurisdiction,jurisLabel,variable,variableLabel,varValue,varValueLabel,value,isStatDisplayable,errorFlag
0,2011,R3,2011,2,Grade 8,MN:MN,WRI,8,WRIRP,NP,National public,GENDER,Sex,1,Male,139.099505,1,0
1,2011,R3,2011,2,Grade 8,MN:MN,WRI,8,WRIRP,NP,National public,GENDER,Sex,2,Female,158.567105,1,0

## 1.2 What happens if there's an error in our query?

In [4]:
## here's a query that from the documentation we know
## won't work since i modified year to 2025 which doesnt
## exist in the data
wrong_naep_query = (
'https://www.nationsreportcard.gov/'
'Dataservice/GetAdhocData.aspx?'
'type=data&subject=writing&grade=8&'
'subscale=WRIRP&variable=GENDER&jurisdiction=NP&stattype=MN:MN&Year=2025')

wrong_naep_query

'https://www.nationsreportcard.gov/Dataservice/GetAdhocData.aspx?type=data&subject=writing&grade=8&subscale=WRIRP&variable=GENDER&jurisdiction=NP&stattype=MN:MN&Year=2025'

In [5]:
## use requests to call the api
naep_wrong_resp = requests.get(wrong_naep_query)
naep_wrong_resp

In [6]:
## in the case of this particular api,
## the call returns some response but
## when we try to extract the json containing
## status or results, we get in an error
#naep_wrong_resp.json() # uncomment to see error

### 1.2.2 More all-purpose way of allowing remainder of calls to run: try, except

In [7]:
## putting it in a try; except as general error catching
try:
    results = naep_wrong_resp.json()['result']
except Exception as e:
    print('Failed to get result from API due to error:')
    print(e) # or just: pass

Failed to get result from API due to error:
Invalid control character at: line 1 column 293 (char 292)

### 1.2.3 Can usually also find more targeted way but that varies more across APIs

In [ ]:
## if we wanted do more specific error catching,
## see that the status == 400 actually appears here
## so could write if else along those lines
naep_wrong_resp.text
naep_resp.text

if "System.Exception" in naep_wrong_resp.text:
    print("NAEP results not found")

## Activity 1: writing a function to make multiple, sequential calls

- Say we want to pull the data for grades 4, 8, and 12
- How can we write a function that iterates over a list of those grades and pulls the data for each grade?

**Note**: an ideal function would have arguments for each parameter in the API like subject, subscale, etc. Here we can leave those other parts constant

In [8]:
# your code here

# 2. Example 2: needs credentials; no wrapper

Create an account here: https://www.yelp.com/developers/v3/manage_app

In [9]:
## get the key
API_KEY = "t1A8Xqn1RN9hZYnHmLGmZ2q-30-Mqk7noeOtqNoEbbWxwmWlDWB0zTVLUuCMapIGa97d8pyb9c_K27E-IREpURt-gFUhMQpo692L6_jepFObCBwMQTPhsWwExpp0anYx"

In [10]:
## use documentation to define what to search
## doc: https://www.yelp.com/developers/documentation/v3/business_search
## write the query 
base_url = "https://api.yelp.com/v3/businesses/search?"
my_name = "restaurants"
my_location = "Hanover,NH,03755"
yelp_genquery = ('{base_url}'
                'term={name}'
                '&location={loc}').format(base_url = base_url,
                name = my_name,
                loc = my_location)

## use requests to call the API; here, we're
## passing it our credentials (structure varies
## by API and telling it to only return 10 results
## (max is 50 at once)
header = {'Authorization': f"Bearer {API_KEY}"}
yelp_genresp = requests.get(yelp_genquery, headers = header)
yelp_genresp

## then, look at structure of response
yelp_genjson = yelp_genresp.json()

In [12]:
## example business
yelp_genjson['businesses'][0]

## more automatic way of summarizing but things end up in lists
## within columns for things like categories
yelp_gendf = pd.DataFrame(yelp_genjson['businesses'])
yelp_gendf.head()

{'id': '8ybF6YyRldtZmU9jil4xlg',
 'alias': 'mollys-restaurant-and-bar-hanover',
 'name': "Molly's Restaurant & Bar",
 'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/TJLrrA6z-SnPgZfrs2GQNQ/o.jpg',
 'is_closed': False,
 'url': 'https://www.yelp.com/biz/mollys-restaurant-and-bar-hanover?adjust_creative=eQYW8f2PoP2KTv7QR4Sa2A&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=eQYW8f2PoP2KTv7QR4Sa2A',
 'review_count': 582,
 'categories': [{'alias': 'tradamerican', 'title': 'American'},
  {'alias': 'burgers', 'title': 'Burgers'},
  {'alias': 'pizza', 'title': 'Pizza'}],
 'rating': 3.9,
 'coordinates': {'latitude': 43.701144, 'longitude': -72.2894249},
 'transactions': ['delivery'],
 'price': '$$',
 'location': {'address1': '43 South Main St',
  'address2': '',
  'address3': '',
  'city': 'Hanover',
  'zip_code': '03755',
  'country': 'US',
  'state': 'NH',
  'display_address': ['43 South Main St', 'Hanover, NH 03755']},
 'phone': '+16036432570',
 'display_phone': '(603) 643-2570',
 'distance': 250.8301601841674,
 'business_hours': [{'open': [{'is_overnight': False,
     'start': '1130',
     'end': '2200',
     'day': 0},
    {'is_overnight': False, 'start': '1130', 'end': '2200', 'day': 1},
    {'is_overnight': False, 'start': '1130', 'end': '2200', 'day': 2},
    {'is_overnight': False, 'start': '1130', 'end': '2200', 'day': 3},
    {'is_overnight': False, 'start': '1130', 'end': '0000', 'day': 4},
    {'is_overnight': False, 'start': '1130', 'end': '0000', 'day': 5},
    {'is_overnight': False, 'start': '1130', 'end': '2200', 'day': 6}],
   'hours_type': 'REGULAR',
   'is_open_now': False}],
 'attributes': {'menu_url': 'http://www.mollysrestaurant.com/uploadcache/Mollys-Menu.pdf'}}

,id,alias,name,image_url,is_closed,url,review_count,categories,rating,coordinates,transactions,price,location,phone,display_phone,distance,business_hours,attributes
0,8ybF6YyRldtZmU9jil4xlg,mollys-restaurant-and-bar-hanover,Molly's Restaurant & Bar,https://s3-media0.fl.yelpcdn.com/bphoto/TJLrrA...,False,https://www.yelp.com/biz/mollys-restaurant-and...,582,"[{'alias': 'tradamerican', 'title': 'American'...",3.9,"{'latitude': 43.701144, 'longitude': -72.2894249}",[delivery],$$,"{'address1': '43 South Main St', 'address2': '...",+16036432570,(603) 643-2570,250.830160,"[{'open': [{'is_overnight': False, 'start': '1...",{'menu_url': 'http://www.mollysrestaurant.com/...
1,JFE0XffhpP3Bi3DQRvymVg,little-havana-hanover,Little Havana,https://s3-media0.fl.yelpcdn.com/bphoto/941vaR...,False,https://www.yelp.com/biz/little-havana-hanover...,29,"[{'alias': 'cuban', 'title': 'Cuban'}, {'alias...",4.9,"{'latitude': 43.700743, 'longitude': -72.287599}","[delivery, pickup]",NaN,"{'address1': '15 Lebanon St', 'address2': '', ...",+18383831000,(838) 383-1000,102.833229,"[{'open': [{'is_overnight': False, 'start': '1...",{'menu_url': 'https://www.canva.com/design/DAG...
2,XVGEEIH5rVB2QzW-qywcJw,base-camp-cafe-hanover,Base Camp Cafe,https://s3-media0.fl.yelpcdn.com/bphoto/tScZeo...,False,https://www.yelp.com/biz/base-camp-cafe-hanove...,264,"[{'alias': 'himalayan', 'title': 'Himalayan/Ne...",4.4,"{'latitude': 43.700626, 'longitude': -72.2887803}",[delivery],$$,"{'address1': '3 Lebanon St', 'address2': 'Ste ...",+16036432007,(603) 643-2007,196.139758,"[{'open': [{'is_overnight': False, 'start': '1...",{'menu_url': 'http://basecampcafenewhampshire....
3,wyV_NfYn4ZOfp_sHMDPcAw,bistro-at-six-hanover,Bistro at Six,https://s3-media0.fl.yelpcdn.com/bphoto/i4jvss...,False,https://www.yelp.com/biz/bistro-at-six-hanover...,2,"[{'alias': 'lounges', 'title': 'Lounges'}, {'a...",4.0,"{'latitude': 43.7001146, 'longitude': -72.2877...",[],$$,"{'address1': '6 E South St', 'address2': '', '...",+16036430600,(603) 643-0600,198.651788,"[{'open': [{'is_overnight': True, 'start': '00...",{}
4,1Q9gTry0GH2NFA7O398xeA,casa-brava-tapas-hanover,Casa Brava Tapas,https://s3-media0.fl.yelpcdn.com/bphoto/fA3__V...,False,https://www.yelp.com/biz/casa-brava-tapas-hano...,10,"[{'alias': 'tapasmallplates', 'title': 'Tapas/...",4.8,"{'latitude': 43.70019133305323, 'longitude': -...",[],NaN,"{'address1': '6 South St', 'address2': '', 'ad...",+16038509763,(603) 850-9763,202.701925,"[{'open': [{'is_overnight': False, 'start': '1...",{'menu_url': 'https://casabravatapas.com/tapas...

In [51]:
## more data-specific way of summarizing
## we're doing a simple approach and just retaining
## cols that have a simple str structure
## if doing for real, would want to extract things
def clean_yelp_json(one_biz):

    ## restrict to str cols
    d_str = {key:value for key, value in one_biz.items()
             if type(value) == str}
    
    df_str = pd.DataFrame(d_str, index = [d_str['id']])
    return(df_str)

yelp_stronly = [clean_yelp_json(one_b) for one_b in yelp_genjson['businesses']]
yelp_stronly_df = pd.concat(yelp_stronly)

yelp_stronly_df.head(7)

,id,alias,name,image_url,url,phone,display_phone,price
-4fGYNfRa-hiiU1hCVFUEw,-4fGYNfRa-hiiU1hCVFUEw,twinflame-oakland,Twinflame,https://s3-media0.fl.yelpcdn.com/bphoto/76RheI...,https://www.yelp.com/biz/twinflame-oakland?adj...,,,NaN
L7I_bhmMacR1lcVUuWwuKg,L7I_bhmMacR1lcVUuWwuKg,almond-and-oak-oakland-2,Almond & Oak,https://s3-media0.fl.yelpcdn.com/bphoto/8vYz42...,https://www.yelp.com/biz/almond-and-oak-oaklan...,+15102509550,(510) 250-9550,$$
D_yAQ4tHlWp2CJSqFCeW_w,D_yAQ4tHlWp2CJSqFCeW_w,mama-oakland-oakland,MAMA Oakland,https://s3-media0.fl.yelpcdn.com/bphoto/uH7mYb...,https://www.yelp.com/biz/mama-oakland-oakland?...,+15109746372,(510) 974-6372,$$$
5x-d9REDONrMabzr9GBm4A,5x-d9REDONrMabzr9GBm4A,sirene-oakland-2,Sirene,https://s3-media0.fl.yelpcdn.com/bphoto/K91CJr...,https://www.yelp.com/biz/sirene-oakland-2?adju...,+15102008750,(510) 200-8750,NaN
Q7RiDz9I2PpltrOnnIfDyg,Q7RiDz9I2PpltrOnnIfDyg,bardo-lounge-and-supper-club-oakland,Bardo Lounge & Supper Club,https://s3-media0.fl.yelpcdn.com/bphoto/H03Q77...,https://www.yelp.com/biz/bardo-lounge-and-supp...,+15108368737,(510) 836-8737,$$$
EEQ_AjO0ErwoF1vkjm5-tg,EEQ_AjO0ErwoF1vkjm5-tg,lucuma-kitchen-and-bar-oakland,Lucuma Kitchen and Bar,https://s3-media0.fl.yelpcdn.com/bphoto/m8yVCu...,https://www.yelp.com/biz/lucuma-kitchen-and-ba...,+15106078110,(510) 607-8110,NaN
tljZfh7_dfmsU36o_vr_uw,tljZfh7_dfmsU36o_vr_uw,the-peach-oakland,The Peach,https://s3-media0.fl.yelpcdn.com/bphoto/RMrmJx...,https://www.yelp.com/biz/the-peach-oakland?adj...,+15109073892,(510) 907-3892,$$

# Activity 2: pull restaurants in a different location

- Try running a business search query for your hometown or another place by constructing a query similar to `yelp_genquery` but changing the location parameter
- Other endpoints require feeding what's called the business' fusion id into the API. Take an id from `yelp_stronly.id` and use the documentation here to pull the reviews for that business: https://docs.developer.yelp.com/reference/v3_business_reviews
- **Challenge**: generalize the previous step by writing a function that (1) takes a list of business ids as an input, (2) calls the reviews API for each id, (3) returns the results, and (4) rowbinds all results, i.e. turns them into a single, usable DataFrame

In [46]:
## use documentation to define what to search
## doc: https://www.yelp.com/developers/documentation/v3/business_search
## write the query 
base_url = "https://api.yelp.com/v3/businesses/search?"
my_name = "restaurants"
my_location = "Oakland,CA,94610"
yelp_genquery = ('{base_url}'
                'term={name}'
                '&location={loc}').format(base_url = base_url,
                name = my_name,
                loc = my_location)

## use requests to call the API; here, we're
## passing it our credentials (structure varies
## by API and telling it to only return 10 results
## (max is 50 at once)
header = {'Authorization': f"Bearer {API_KEY}"}
yelp_genresp = requests.get(yelp_genquery, headers = header)
yelp_genresp

## then, look at structure of response
yelp_genjson = yelp_genresp.json()

#yelp_genjson

business_id = yelp_genjson["businesses"][0]["id"]
print(business_id)
yelp_genquery=("https://api.yelp.com/v3/businesses/{business_id_or_alias}/reviews").format(business_id_or_alias = business_id)
header = {'Authorization': f"Bearer {API_KEY}"}
yelp_business = requests.get(yelp_genquery, headers = header)
yelp_business

-4fGYNfRa-hiiU1hCVFUEw

In [52]:
import requests
API_KEY = "rAZn1RX6Tr2o999Ly8EvD6ofsNGBZg3CMDsDxAwKGTEdWIi1zm9g23h_1ll5oix2Z0hSDiRloteTewU35nBqydGvoq0LngcGlZPP6LERVywiS_uc18KMmtvg9qQuZXYx"
url = "https://api.yelp.com/v3/businesses/Ecdu5qYM09F647Uoez99vg/reviews?"
header = {'Authorization': f'Bearer {API_KEY}'}
response = requests.get(url, headers=header)
print(response.text)

{"reviews": [{"id": "qUGeiKnzJaY4ldELiyUxVA", "url": "https://www.yelp.com/biz/ramuntos-brick-and-brew-pizzeria-hanover?adjust_creative=ZmitoFfF-pb6UbUwNTC3_A&hrid=qUGeiKnzJaY4ldELiyUxVA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=ZmitoFfF-pb6UbUwNTC3_A", "text": "The famous garlic knot pizza is a must try. My friend and I split a large (okay... way too big for 2 lol) and we both could barely finish 2 slices each...", "rating": 4.0, "time_created": "2026-06-26 11:48:37", "user": {"id": "kYf0AgTRNfhV6giPT3anpQ", "profile_url": "https://www.yelp.com/user_details?userid=kYf0AgTRNfhV6giPT3anpQ", "image_url": "https://s3-media0.fl.yelpcdn.com/photo/4-DvlQkWB00d-C7hfDpK2w/o.jpg", "name": "Cleo G."}}, {"id": "KMBiy0t5YTnmvLMR2i60rA", "url": "https://www.yelp.com/biz/ramuntos-brick-and-brew-pizzeria-hanover?adjust_creative=ZmitoFfF-pb6UbUwNTC3_A&hrid=KMBiy0t5YTnmvLMR2i60rA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=ZmitoFfF-pb6UbUwNTC3_A", "text": "I order online the meditterran pizza added shrimp. I should have left them off. No flavor what so ever. Just threw cold shrimp and pizza and baked. I guess...", "rating": 3.0, "time_created": "2025-12-31 10:16:26", "user": {"id": "0G71iWXvXqibG9Lzrwg8Gg", "profile_url": "https://www.yelp.com/user_details?userid=0G71iWXvXqibG9Lzrwg8Gg", "image_url": "https://s3-media0.fl.yelpcdn.com/photo/gejQv2RVbe3T6ESVAacJZA/o.jpg", "name": "Wan G."}}, {"id": "j18Xzk5jvO4g-6E9cuxHig", "url": "https://www.yelp.com/biz/ramuntos-brick-and-brew-pizzeria-hanover?adjust_creative=ZmitoFfF-pb6UbUwNTC3_A&hrid=j18Xzk5jvO4g-6E9cuxHig&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_reviews&utm_source=ZmitoFfF-pb6UbUwNTC3_A", "text": "Slices up!!!! \n\nSolid Hanover pizza spot for quick by the slice pizza on the go\n\nPro tip: Thursday's after 8pm they have beer and slice specials...", "rating": 3.0, "time_created": "2025-05-25 09:28:07", "user": {"id": "120Icn9O5C-Xj8pyYsU1MQ", "profile_url": "https://www.yelp.com/user_details?userid=120Icn9O5C-Xj8pyYsU1MQ", "image_url": "https://s3-media0.fl.yelpcdn.com/photo/JX98f8zdJHiC1NbXH7kiBg/o.jpg", "name": "Aleksandar K."}}], "total": 158, "possible_languages": ["en"]}

In [53]:
def reviews(business_ids):
    all_reviews = []
    
    for business_id in business_ids:
        url = ("https://api.yelp.com/v3/businesses/{business_id_or_alias}/reviews").format(business_id_or_alias = business_id)
        response = requests.get(url, headers=header)
        review_list = response.json()["reviews"]
        
        df = pd.json_normalize(review_list)
        df["business_id"] = business_id
        all_reviews.append(df)
        
    return pd.concat(all_reviews, ignore_index=True)

In [57]:
business_ids = [b["id"] for b in yelp_genjson["businesses"]]

In [58]:
reviews(business_ids)

,id,url,text,rating,time_created,user.id,user.profile_url,user.image_url,user.name,business_id
0,Z3D_MIxHDyH6TWx0QkGdyw,https://www.yelp.com/biz/twinflame-oakland?adj...,Amazing loved the food 10/10!\nService is amaz...,5.0,2026-07-18 21:18:19,cofoGO_gazflr1z4HZe8VQ,https://www.yelp.com/user_details?userid=cofoG...,NaN,Nerida I.,-4fGYNfRa-hiiU1hCVFUEw
1,yujm46844ozbHrFLGjuTqA,https://www.yelp.com/biz/twinflame-oakland?adj...,"Twinflame on MacArthur, brand new spot just op...",5.0,2026-08-02 20:27:18,9lvYJ4OZZfF1Lwq7_V1pXA,https://www.yelp.com/user_details?userid=9lvYJ...,https://s3-media0.fl.yelpcdn.com/photo/G6lZpm4...,John S.,-4fGYNfRa-hiiU1hCVFUEw
2,WpXBcdY4v9yF6isHsffXnQ,https://www.yelp.com/biz/twinflame-oakland?adj...,Of course it was an instagram collab that got ...,3.0,2026-08-04 11:10:52,3roJp-RoqKVoMgdtuJFM9Q,https://www.yelp.com/user_details?userid=3roJp...,https://s3-media0.fl.yelpcdn.com/photo/I387jLz...,Christine M.,-4fGYNfRa-hiiU1hCVFUEw
3,S9mZ_ILg-eCYh0TZC2eGOQ,https://www.yelp.com/biz/almond-and-oak-oaklan...,I'm not sure if I was just extremely craving b...,5.0,2026-08-02 09:39:05,VXwiLvqT_qXp9T5iho81Tw,https://www.yelp.com/user_details?userid=VXwiL...,https://s3-media0.fl.yelpcdn.com/photo/5v3p2F8...,Kineshia C.,L7I_bhmMacR1lcVUuWwuKg
4,dS_H4tXtObCyow9yodz35w,https://www.yelp.com/biz/almond-and-oak-oaklan...,Came here for lunch with a friend at 1 PM on a...,4.0,2026-05-12 12:10:58,2PeqtdiehYm82TXymQUGow,https://www.yelp.com/user_details?userid=2Peqt...,https://s3-media0.fl.yelpcdn.com/photo/3OobBd7...,Michelle V.,L7I_bhmMacR1lcVUuWwuKg
5,GFTEQ4k_IAyEN0sPkWkZbQ,https://www.yelp.com/biz/almond-and-oak-oaklan...,Food was good.....service was good.\nHad break...,4.0,2026-04-28 10:25:00,VMHkA0mgHIl0N6YtGuC0hw,https://www.yelp.com/user_details?userid=VMHkA...,https://s3-media0.fl.yelpcdn.com/photo/jdoeChR...,Joy J.,L7I_bhmMacR1lcVUuWwuKg
6,N2GeEOvVnoqXQtkbqgzWzw,https://www.yelp.com/biz/mama-oakland-oakland?...,This is an excellent neighborhood place in a b...,5.0,2026-07-27 17:43:02,K7PYzne7jiH2Ufx_8zV8aA,https://www.yelp.com/user_details?userid=K7PYz...,https://s3-media0.fl.yelpcdn.com/photo/M0NmrLD...,Allure N.,D_yAQ4tHlWp2CJSqFCeW_w
7,IgM3qrAXrJCwkIoOHYgqNQ,https://www.yelp.com/biz/mama-oakland-oakland?...,"We've been coming here for years, and today, m...",4.0,2026-07-12 08:39:11,uHcoVFaNGNrPKVdjN5mvuQ,https://www.yelp.com/user_details?userid=uHcoV...,https://s3-media0.fl.yelpcdn.com/photo/lSRj6NX...,Ted R.,D_yAQ4tHlWp2CJSqFCeW_w
8,7DtOGck81mrzbE0gbHOy-A,https://www.yelp.com/biz/mama-oakland-oakland?...,Mama was recommended to me by a frugal foodie ...,5.0,2026-06-25 18:01:57,V_aMX7kxXf6GfNyFpO32rA,https://www.yelp.com/user_details?userid=V_aMX...,https://s3-media0.fl.yelpcdn.com/photo/KrR5dJA...,Catherine T.,D_yAQ4tHlWp2CJSqFCeW_w
9,xFRTScP-xdKrY5-TrPr0Lw,https://www.yelp.com/biz/sirene-oakland-2?adju...,Sirene absolutely knocked it out of the park.\...,5.0,2026-07-12 21:42:07,Rd873ATgu5aZ9wr2dkU6iQ,https://www.yelp.com/user_details?userid=Rd873...,https://s3-media0.fl.yelpcdn.com/photo/HRbbN9B...,Lin L.,5x-d9REDONrMabzr9GBm4A
10,MCny6SF5QxUJDL0KCNvgzA,https://www.yelp.com/biz/sirene-oakland-2?adju...,Been wanting to try this spot after eating at ...,5.0,2026-07-11 13:23:18,TeTUbh7QCzTT99vI6TwWPA,https://www.yelp.com/user_details?userid=TeTUb...,https://s3-media0.fl.yelpcdn.com/photo/WIJdqMV...,Jessie H.,5x-d9REDONrMabzr9GBm4A
11,BnIxFmJ5MPbwjXRLOD9IzA,https://www.yelp.com/biz/sirene-oakland-2?adju...,Overall good experience. Went there last night...,2.0,2026-07-09 15:26:02,RrTtOvzxQFfjePCOxx5dCg,https://www.yelp.com/user_details?userid=RrTtO...,https://s3-media0.fl.yelpcdn.com/photo/AXj070W...,Jan C.,5x-d9REDONrMabzr9GBm4A
12,b_2vX4SpwuUt93dRHrgVaw,https://www.yelp.com/biz/bardo-lounge-and-supp...,What to say about Bardo! The vibe and decor ar...,5.0,2026-04-26 12:54:36,oq7AnTkM8hmraqIKm9uB2w,https://www.yelp.com/user_details?userid=oq7An...,https://s3-media0.fl.yelpcdn.com/photo/5XQrv6P...,Peter H.,Q7RiDz9I2PpltrOnnIfDyg
13,NNXpjlTrA9A2st3wIs_mXw,https://www.yelp.com/biz/bardo-lounge-and-supp...,"Visiting Oakland from Las Vegas, read great re...",3.0,2026-06-18 21:56:26,cRy-NmcwCs6UMv4brlGPUQ,https://www.yelp.com/user_details?userid=cRy-N...,https://s3-media0.fl.yelpcdn.com/photo/cbaVsq9...,Gracie Y.,Q7RiDz9I2PpltrOnnIfDyg
14,kmiCXF-TCa4WeEbofZY2Fw,https://www.yelp.com/biz/bardo-lounge-and-supp...,This was my first time here and goodness was i...,4.0,2026-04-25 15:45:21,AsLveLBPKstYy96PapfB8A,https://www.yelp.com/user_details?userid=AsLve...,https://s3-media0.fl.yelpcdn.com/photo/5a6Wz9E...,Kay O.,Q7RiDz9I2PpltrOnnIfDyg
15,TJ8UqGDVLuqAQeu385He_A,https://www.yelp.com/biz/lucuma-kitchen-and-ba...,"It looks very nice inside, and you expect the ...",5.0,2026-07-18 13:51:03,RdJqaCDqwMf0q_n_0PmLKQ,https://www.yelp.com/user_details?userid=RdJqa...,NaN,Veronica M.,EEQ_AjO0ErwoF1vkjm5-tg
16,-YQW8nsaAwIqDLWFMXa2WQ,https://www.yelp.com/biz/lucuma-kitchen-and-ba...,"So many gluten free options, and as a celiac t...",5.0,2026-08-02 10:28:03,QjWDEmrQjJTYcBbZV3zMxQ,https://www.yelp.com/user_details?userid=QjWDE...,https://s3-media0.fl.yelpcdn.com/photo/xp69XwV...,Tera E.,EEQ_AjO0ErwoF1vkjm5-tg
17,bqGi6SWu2I5il5Y9w0kVrg,https://www.yelp.com/biz/lucuma-kitchen-and-ba...,Let me just start up by saying how much I love...,5.0,2026-07-31 11:53:32,N661MNj0cMItlwumGSCiGg,https://www.yelp.com/user_details?userid=N661M...,https://s3-media0.fl.yelpcdn.com/photo/fK8g32c...,Max Y.,EEQ_AjO0ErwoF1vkjm5-tg
18,TYFfvqimTV28bIyoVY_jdw,https://www.yelp.com/biz/the-peach-oakland?adj...,first time here and it exceeded my expectation...,5.0,2026-06-25 12:21:29,Vqk5oqZmY0GjPsXuqWorHA,https://www.yelp.com/user_details?userid=Vqk5o...,NaN,Lorena V.,tljZfh7_dfmsU36o_vr_uw
19,o1GGBl-SYuJYDvgsunKgsg,https://www.yelp.com/biz/the-peach-oakland?adj...,food:\nchef harold's omlette: 5/5 \nvery yummy...,5.0,2026-07-28 19:48:11,mfikUv4VHC8s2p7mLnAGew,https://www.yelp.com/user_details?userid=mfikU...,https://s3-media0.fl.yelpcdn.com/photo/n3YrgKG...,John L.,tljZfh7_dfmsU36o_vr_uw
20,ZZ3mkxKechfJoueqHgoF3g,https://www.yelp.com/biz/the-peach-oakland?adj...,-Excellent shrimp and grits- almost licked the...,4.0,2026-07-16 01:17:58,8odT-O6PSwXnpl10YmPobQ,https://www.yelp.com/user_details?userid=8odT-...,https://s3-media0.fl.yelpcdn.com/photo/OkAWcB_...,Rachel V.,tljZfh7_dfmsU36o_vr_uw
21,mSoFVOdrN7kgc2K-0sGdKg,https://www.yelp.com/biz/town-biscuits-oakland...,*GASP* There aren't many places like Town Bisc...,5.0,2026-08-03 15:30:03,GwRvjqhVRxzjhfSV322wNg,https://www.yelp.com/user_details?userid=GwRvj...,https://s3-media0.fl.yelpcdn.com/photo/A4a02Ot...,Brima J.,w9AXw4JQ80dDsd0cd38cig
22,6uX2Ev0IHMuoDYpNuWHTuA,https://www.yelp.com/biz/town-biscuits-oakland...,We walked in on a Saturday around 11:30am and ...,5.0,2026-07-26 20:54:24,j-ZYFQ9N_nXW9ETkYk5WXA,https://www.yelp.com/user_details?userid=j-ZYF...,https://s3-media0.fl.yelpcdn.com/photo/xmLzmf4...,Francina L.,w9AXw4JQ80dDsd0cd38cig
23,QvNa9ZTDRAuFA7CDW82msA,https://www.yelp.com/biz/town-biscuits-oakland...,We were in town looking for a quick breakfast ...,5.0,2026-07-13 13:01:30,KjXID5UvwxS1-TRAsw2aYw,https://www.yelp.com/user_details?userid=KjXID...,https://s3-media0.fl.yelpcdn.com/photo/kNqBuB7...,Cathy B.,w9AXw4JQ80dDsd0cd38cig
24,m3wPv49gIwRigt3Eaa4kqQ,https://www.yelp.com/biz/parche-oakland?adjust...,Great date night or girls dinner spot! When th...,5.0,2026-07-22 09:18:06,Vga0wiLJ2z2XrG5jl9qA8g,https://www.yelp.com/user_details?userid=Vga0w...,https://s3-media0.fl.yelpcdn.com/photo/43NWD8m...,Kristina M.,XuIhJp2WukLPI9iJGUXiAQ
25,Qqv7K4ksQ1cm-7Hp6XvN7A,https://www.yelp.com/biz/parche-oakland?adjust...,Parche has a lot going for it. The service was...,4.0,2026-07-22 19:45:06,pJBNY8cW0c7zAyjFKOP3kg,https://www.yelp.com/user_details?userid=pJBNY...,https://s3-media0.fl.yelpcdn.com/photo/iRiC23o...,Ili S.,XuIhJp2WukLPI9iJGUXiAQ
26,TA1RYiZY1iHqT_HZiERq6Q,https://www.yelp.com/biz/parche-oakland?adjust...,"Oh wow, that was a real treat! I love their de...",4.0,2026-07-20 15:39:51,lUSOwEi7PQk3PF_7u7aN-Q,https://www.yelp.com/user_details?userid=lUSOw...,https://s3-media0.fl.yelpcdn.com/photo/WqJywg_...,Alexa W.,XuIhJp2WukLPI9iJGUXiAQ
27,BEYumlfgOBRg2o2Our14rw,https://www.yelp.com/biz/grand-lake-kitchen-la...,Stopped by Grand Lake Kitchen for brunch this ...,5.0,2026-03-15 18:12:14,PQfXSaGGEA2Q9CnsZ4jffA,https://www.yelp.com/user_details?userid=PQfXS...,https://s3-media0.fl.yelpcdn.com/photo/g3Z7Y5d...,Isabel M.,7UjYrhJ6_ggqkfsp-B9iCA
28,HnoOk-B3-rX_VNq3h0YkJQ,https://www.yelp.com/biz/grand-lake-kitchen-la...,This was me and my husband's first time at the...,2.0,2026-04-21 10:50:40,Py8-FZvWE07oYlLR2t6FHQ,https://www.yelp.com/user_details?userid=Py8-F...,https://s3-media0.fl.yelpcdn.com/photo/QB3d1S6...,Mercedes H.,7UjYrhJ6_ggqkfsp-B9iCA
29,VjRVrIAzlfcfFHPOpi6JCw,https://www.yelp.com/biz/grand-lake-kitchen-la...,This is a lovely brunch spot before you take a...,4.0,2026-03-14 08:10:56,wTevVlJuQ0OzZvxsVS9nbg,https://www.yelp.com/user_details?userid=wTevV...,https://s3-media0.fl.yelpcdn.com/photo/5S1l8Ca...,Viviana H.,7UjYrhJ6_ggqkfsp-B9iCA
30,bfcDzOC1OFG964vCxnV6QQ,https://www.yelp.com/biz/mensho-oakland?adjust...,Mensho is a very popular restaurant. This was ...,5.0,2026-06-19 20:57:59,e0QNMIHhmP4SGpkRa5zgNQ,https://www.yelp.com/user_details?userid=e0QNM...,https://s3-media0.fl.yelpcdn.com/photo/rP0g4i7...,Sam T.,aIyO-hJXGwgJt3jpZIzz6Q
31,SOtXqkgs-17crqqINuKnOw,https://www.yelp.com/biz/mensho-oakland?adjust...,Unfortunately no photos as we devoured the foo...,4.0,2026-07-17 09:05:34,iNNudnNIfRn89CkAEMUHlg,https://www.yelp.com/user_details?userid=iNNud...,https://s3-media0.fl.yelpcdn.com/photo/3_tIGVY...,Dan B.,aIyO-hJXGwgJt3jpZIzz6Q
32,UfpSovfxDRnZAxIoHs9cKA,https://www.yelp.com/biz/mensho-oakland?adjust...,Unpopular opinion: wasn't my favorite. But tha...,2.0,2026-06-08 21:08:57,IYDjPjn2oHwncnjNuCOzSA,https://www.yelp.com/user_details?userid=IYDjP...,https://s3-media0.fl.yelpcdn.com/photo/qB_UFKH...,Jill G.,aIyO-hJXGwgJt3jpZIzz6Q
33,tVrAqsrcrEv898sQtAJpuA,https://www.yelp.com/biz/popoca-oakland-oaklan...,"Popoca was everything and more!!\nFirst, shout...",5.0,2026-08-05 12:14:53,v8zPGtnaUiwZZTbfXc8naQ,https://www.yelp.com/user_details?userid=v8zPG...,https://s3-media0.fl.yelpcdn.com/photo/HK1BbRf...,Marissa M.,5T8x532FlUIRzx3iMp8A2g
34,FdTfn87TKSE7VnIYZEZTaQ,https://www.yelp.com/biz/popoca-oakland-oaklan...,Finally got a reservation at Popoca! Needed to...,5.0,2026-08-02 15:02:23,uTonkXPJysh8WLRp7ISffQ,https://www.yelp.com/user_details?userid=uTonk...,https://s3-media0.fl.yelpcdn.com/photo/rX9CKWV...,Phil H.,5T8x532FlUIRzx3iMp8A2g
35,4UUfcFC506XIKtg6MTsbhQ,https://www.yelp.com/biz/popoca-oakland-oaklan...,Popoca is in the Old Oakland Neighborhood at t...,5.0,2026-07-27 07:25:15,ls9Z1mRQ9m4sYG4f-WzoUA,https://www.yelp.com/user_details?userid=ls9Z1...,https://s3-media0.fl.yelpcdn.com/photo/P8QY1rv...,Mike L.,5T8x532FlUIRzx3iMp8A2g
36,uupsWdTJenXDKR24DvrpfA,https://www.yelp.com/biz/the-wolf-oakland?adju...,"Great food , ambiance , friendly staff!\n\nOn ...",5.0,2026-06-30 12:34:03,UiJCuzSuq1Jj0UwnWL2Lcg,https://www.yelp.com/user_details?userid=UiJCu...,NaN,Suzy S.,6MXjFD232pQ38pgY9tY66g
37,clzogJhKoW274giXmZMRvA,https://www.yelp.com/biz/the-wolf-oakland?adju...,The Wolf was Fantastic. My guest and I went fo...,5.0,2026-07-19 13:24:59,rUg628ONInlYn_XzWugAGQ,https://www.yelp.com/user_details?userid=rUg62...,https://s3-media0.fl.yelpcdn.com/photo/EiKrvwf...,Michelle N.,6MXjFD232pQ38pgY9tY66g
38,awit_zTlul9cHfqmNtRyXA,https://www.yelp.com/biz/the-wolf-oakland?adju...,"I ordered Octopus, Pork Chop, Duck Breast, Hal...",2.0,2026-08-05 07:23:54,OGgupSywGeLEfShQSHx7qw,https://www.yelp.com/user_details?userid=OGgup...,https://s3-media0.fl.yelpcdn.com/photo/pzO2DtO...,Tom L.,6MXjFD232pQ38pgY9tY66g
39,dJC5YmhaZGopYrb9r96cmQ,https://www.yelp.com/biz/obelisco-restaurant-o...,The photos show the chicken molé and the enchi...,5.0,2026-06-23 19:01:58,7GMidwC4FuZ6uT6zYjVu3w,https://www.yelp.com/user_details?userid=7GMid...,https://s3-media0.fl.yelpcdn.com/photo/H5cc9CU...,Freddie M.,o5a9XnH115C4UQlZS6GG9A
40,tM2LBfEQXEGGD1qJIX1nlQ,https://www.yelp.com/biz/obelisco-restaurant-o...,I was walking along Lakeshore when I had the u...,4.0,2026-07-16 18:56:40,xH3ybNhyA29OLtIEquV2Vg,https://www.yelp.com/user_details?userid=xH3yb...,https://s3-media0.fl.yelpcdn.com/photo/-d1PIpD...,Sheila J.,o5a9XnH115C4UQlZS6GG9A
41,n5F3q3tGgrfMdhNcjEZdAg,https://www.yelp.com/biz/obelisco-restaurant-o...,Things I liked:\nThe food! Delicious and fresh...,4.0,2026-07-13 07:26:14,tvh9_9WTSqh_6RLSPilltg,https://www.yelp.com/user_details?userid=tvh9_...,https://s3-media0.fl.yelpcdn.com/photo/ZFG2SxM...,Vince D.,o5a9XnH115C4UQlZS6GG9A
42,jMkZ_dHEMYgr80z8gDu6IA,https://www.yelp.com/biz/bar-skula-oakland?adj...,We loved our dinner at Bar Skúla and are so ha...,5.0,2026-08-05 11:06:38,YRFuhOXJyHsPUuVmH75KMA,https://www.yelp.com/user_details?userid=YRFuh...,https://s3-media0.fl.yelpcdn.com/photo/THMVju6...,Susan T.,iyjUGC89Qx4nBMbAhPs2uA
43,MYB1M7Ru3m8FSUJpuVM0Pw,https://www.yelp.com/biz/bar-skula-oakland?adj...,Drinks 100 stars \nFood - still discovering. S...,5.0,2026-07-31 21:24:59,2M3DEZSIPZdASESenz8JpA,https://www.yelp.com/user_details?userid=2M3DE...,https://s3-media0.fl.yelpcdn.com/photo/tom3zC1...,Marcy S.,iyjUGC89Qx4nBMbAhPs2uA
44,iQgnSAsxgAE9AvpzJmvPig,https://www.yelp.com/biz/bar-skula-oakland?adj...,Went here last Sunday for a light dinner. The ...,5.0,2026-07-30 11:40:13,cKtzEjVKgXmCgcEveEeXGQ,https://www.yelp.com/user_details?userid=cKtzE...,https://s3-media0.fl.yelpcdn.com/photo/y4Rbywh...,John D.,iyjUGC89Qx4nBMbAhPs2uA
45,ZBGwT0PyWGfXCcZHUoHOnQ,https://www.yelp.com/biz/paulista-oakland-2?ad...,My boyfriend and I gave this place a try over ...,4.0,2026-08-03 05:23:48,a-WqWlnbHEWg539aamDHXw,https://www.yelp.com/user_details?userid=a-WqW...,https://s3-media0.fl.yelpcdn.com/photo/nJXh-5m...,Melia R.,7pj79EX2hQcrscKeXXbvSQ
46,FFW7ig6eOo63yQ1yitvdpQ,https://www.yelp.com/biz/paulista-oakland-2?ad...,"Excellent food, amazing beer selection and gre...",5.0,2026-08-01 17:05:51,uAGW1zOh68Ytxid15-o6cg,https://www.yelp.com/user_details?userid=uAGW1...,NaN,John A.,7pj79EX2hQcrscKeXXbvSQ
47,2PVvw6QsDJR5QHwltYsDlg,https://www.yelp.com/biz/paulista-oakland-2?ad...,Chill vibes and excellent selection of beers a...,4.0,2026-05-08 02:37:16,xDRMbT2_tawTHbujRaZSZw,https://www.yelp.com/user_details?userid=xDRMb...,https://s3-media0.fl.yelpcdn.com/photo/xXbiXM5...,Tom K.,7pj79EX2hQcrscKeXXbvSQ
48,yXW11POf-2L8L59RAr0wQQ,https://www.yelp.com/biz/bistro-4293-oakland?a...,Phenomenal!\n\nWe had calamari as well as the ...,5.0,2026-07-24 11:24:06,c2Ni-7hKiWWxFhIk868C3Q,https://www.yelp.com/user_details?userid=c2Ni-...,https://s3-media0.fl.yelpcdn.com/photo/HXSovrj...,Anurag P.,O_4l6IJZmMyDxNkX173aEw
49,mUtljcC2JK0Odb9f2y_IVw,https://www.yelp.com/biz/bistro-4293-oakland?a...,"...I'll start off by saying, ""I love Mediterra...",4.0,2026-05-02 22:21:38,DlHFYzdRg3lxrsy5uOVRWA,https://www.yelp.com/user_details?userid=DlHFY...,https://s3-media0.fl.yelpcdn.com/photo/ZS-LuUO...,Ron B.,O_4l6IJZmMyDxNkX173aEw
50,WDBCToSapZ0z5QvH7dJi0w,https://www.yelp.com/biz/bistro-4293-oakland?a...,We went to Bistro 4293 to celebrate our friend...,5.0,2026-07-06 13:47:21,K3CfyTuzMg4VxBzXmCNKQA,https://www.yelp.com/user_details?userid=K3Cfy...,https://s3-media0.fl.yelpcdn.com/photo/fr5NhgB...,Mark E.,O_4l6IJZmMyDxNkX173aEw
51,xonzi7SB7WLN2NvD3lGDyQ,https://www.yelp.com/biz/my-friend-fernando-oa...,We've had the pleasure of experiencing Chef Ja...,5.0,2023-04-29 14:49:47,aFg_O9ULQ-N6pjDqJGPB-g,https://www.yelp.com/user_details?userid=aFg_O...,https://s3-media0.fl.yelpcdn.com/photo/tCnOx3Q...,Rene S.,-QXGhE7FQ2_DkdfycbcVLw
52,cGtBepl6Us9M2SS9tAaCgg,https://www.yelp.com/biz/my-friend-fernando-oa...,"A once a month pop-up, I planned my entire wee...",5.0,2021-08-17 09:21:46,Ae1atVuqSF8r5QkchacXVg,https://www.yelp.com/user_details?userid=Ae1at...,https://s3-media0.fl.yelpcdn.com/photo/pUoCYBo...,Samir K.,-QXGhE7FQ2_DkdfycbcVLw
53,-rM1oXodx_K8K2jtWYf0QQ,https://www.yelp.com/biz/my-friend-fernando-oa...,I've been fortunate enough to be able to go to...,5.0,2024-01-03 11:56:57,xD_kngj-zekT5j0zve31NA,https://www.yelp.com/user_details?userid=xD_kn...,https://s3-media0.fl.yelpcdn.com/photo/TrYrzE2...,Victoria A.,-QXGhE7FQ2_DkdfycbcVLw
54,9WvN_UHMDq2IbiWx34_4og,https://www.yelp.com/biz/pomet-oakland-2?adjus...,An enjoyable dinner at Pomet with food highlig...,5.0,2026-05-28 21:33:50,GFkOkEpTGcXxHd0-mnNVdw,https://www.yelp.com/user_details?userid=GFkOk...,https://s3-media0.fl.yelpcdn.com/photo/z8uGu9b...,Cheryl M.,VAG7WU0cY7276r0gdDaB9A
55,ueZ2RCLXBzdQ_tOTCMc50A,https://www.yelp.com/biz/pomet-oakland-2?adjus...,"I've been to Pomet at least seven times, usual...",1.0,2026-04-12 19:42:24,ZKHBlI2zb0fkp7Z_4YCDow,https://www.yelp.com/user_details?userid=ZKHBl...,https://s3-media0.fl.yelpcdn.com/photo/_F9UtYf...,Lasaunda T.,VAG7WU0cY7276r0gdDaB9A
56,FMkSXcolu0mj8MRiXsKbYQ,https://www.yelp.com/biz/pomet-oakland-2?adjus...,Don't even think about asking for a straw at P...,4.0,2026-01-26 11:16:27,eKUGKQRE-Ywi5dY55_zChg,https://www.yelp.com/user_details?userid=eKUGK...,https://s3-media0.fl.yelpcdn.com/photo/0p3TFzv...,Cherylynn N.,VAG7WU0cY7276r0gdDaB9A
57,i6P6NoAlUcNXPagxEWYK1w,https://www.yelp.com/biz/yellow-door-oakland?a...,Food is amazing! And reasonably priced! Coffee...,5.0,2026-06-18 09:59:28,V2iPqOmaa6ArMk88tjPq9g,https://www.yelp.com/user_details?userid=V2iPq...,https://s3-media0.fl.yelpcdn.com/photo/tZsDRhD...,Erica Y.,e7WBJvlEfnIkvV8a3Y4IPQ
58,vT59wMFZAblzcG3PKwz2Cw,https://www.yelp.com/biz/yellow-door-oakland?a...,I popped in real quick before work. I was star...,3.0,2026-07-07 20:23:18,2M3DEZSIPZdASESenz8JpA,https://www.yelp.com/user_details?userid=2M3DE...,https://s3-media0.fl.yelpcdn.com/photo/tom3zC1...,Marcy S.,e7WBJvlEfnIkvV8a3Y4IPQ
59,coYTeQ0ki1xhcwEJhwrfuQ,https://www.yelp.com/biz/yellow-door-oakland?a...,My friends and I stopped by Yellow Door on a S...,3.0,2026-04-21 11:17:07,REWjbYaUkmGw04lNZraeQA,https://www.yelp.com/user_details?userid=REWjb...,https://s3-media0.fl.yelpcdn.com/photo/gl4LW5M...,Austin W.,e7WBJvlEfnIkvV8a3Y4IPQ